version: '3.9'
services:
  auction-db:
    image: postgres
    restart: always
    container_name: auction-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATE: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: